# dim_municipios

### Libs

In [1]:
%run ../../config/bootstrap.py

In [2]:
import pandas as pd
from datetime import datetime 
from utils import get_project_root, save_parquet_in_chunks  
import basedosdados as bd

In [3]:
project_root = get_project_root() 
#billing_id = 'ufrgs-ppgc-dengue'

In [4]:
#%load_ext sql
%reload_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.displaylimit = 100
%sql bigquery://ufrgs-ppgc-dengue

Connecting to 'bigquery://ufrgs-ppgc-dengue'

# Dicionário

## ⌛ Staging

In [5]:
output = project_root / "data/4_gold/dim_municipios_avs/dim_municipios_avs"

In [6]:
%%sql 
select distinct raca_cor, sexo FROM `basedosdados.br_ipea_avs.municipio` AS dados

Running query in 'bigquery://ufrgs-ppgc-dengue'

9 rows affected.

  raca_cor    sexo
0   branco   homem
1    total   homem
2    negro   homem
3   branco   total
4    total   total
5    negro   total
6   branco  mulher
7    total  mulher
8    negro  mulher

In [15]:
%%sql
SELECT nome_regiao, 
    sigla_uf, nome_regiao_saude,
    id_municipio,
    nome, 
    centroide,*
FROM `basedosdados.br_bd_diretorios_brasil.municipio`
where id_municipio='4314902' limit 10

Running query in 'bigquery://ufrgs-ppgc-dengue'

1 rows affected.

,nome_regiao,sigla_uf,nome_regiao_saude,id_municipio,nome,centroide,id_municipio_1,id_municipio_6,id_municipio_tse,id_municipio_rf,id_municipio_bcb,nome_1,capital_uf,id_comarca,id_regiao_saude,nome_regiao_saude_1,id_regiao_imediata,nome_regiao_imediata,id_regiao_intermediaria,nome_regiao_intermediaria,id_microrregiao,nome_microrregiao,id_mesorregiao,nome_mesorregiao,id_regiao_metropolitana,nome_regiao_metropolitana,ddd,id_uf,sigla_uf_1,nome_uf,nome_regiao_1,amazonia_legal,centroide_1
0,Sul,RS,Região 10 - Capital e Vale do Gravataí,4314902,Porto Alegre,POINT(-51.1651355343198 -30.0953153270686),4314902,431490,88013,8801,3681,Porto Alegre,1,4314902,43010,Região 10 - Capital e Vale do Gravataí,430001,Porto Alegre,4301,Porto Alegre,43026,Porto Alegre,4305,Metropolitana de Porto Alegre,7401,Região Metropolitana de Porto Alegre,51,43,RS,Rio Grande do Sul,Sul,0,POINT(-51.1651355343198 -30.0953153270686)

In [28]:
%%sql
select sigla_uf,id_municipio,localizacao,udh,nome_udh
FROM `basedosdados.br_ipea_avs.municipio`
limit 10

Running query in 'bigquery://ufrgs-ppgc-dengue'

10 rows affected.

  sigla_uf id_municipio localizacao    udh nome_udh
0       AC      1200203       rural  geral     None
1       AC      1200138      urbano  geral     None
2       AC      1200807       total  geral     None
3       AC      1200138      urbano  geral     None
4       AC      1200302      urbano  geral     None
5       AP      1600501      urbano  geral     None
6       AM      1303403       total  geral     None
7       AM      1304062       rural  geral     None
8       AM      1300631      urbano  geral     None
9       AM      1302553      urbano  geral     None

In [ ]:
%%sql
select sigla_uf,id_municipio,localizacao,udh,nome_udh, *
FROM `basedosdados.br_ipea_avs.municipio`
where ano=2010 and udh <>'geral' and id_municipio='4314902'
limit 10

Running query in 'bigquery://ufrgs-ppgc-dengue'

10 rows affected.

,sigla_uf,id_municipio,localizacao,udh,nome_udh,ano,sigla_uf_1,id_municipio_1,raca_cor,sexo,localizacao_1,ivs,ivs_infraestrutura_urbana,ivs_capital_humano,ivs_renda_trabalho,udh_1,nome_udh_1,idhm,idhm_l,idhm_e,idhm_r,idhm_subescolaridade,idhm_subfrequencia,prosperidade_social,proporcao_vulnerabilidade_socioeconomica,propocao_energia_eletrica,proporcao_domicilio_densidade,proporcao_sem_agua_esgoto,proporcao_sem_coleta,renda_per_capita,renda_media_18_mais,proporcao_sem_renda_18_mais,renda_trabalho,renda_per_capita_vulneravel,proporcao_vulneravel,populacao_vulneravel_15_24,proporcao_vulneravel_dependente_idoso,populacao_vulneravel_e_idoso,razao_dependencia,fecundidade_total,taxa_envelhecimento,mortalidade_1_menos,proporcao_mortalidade_5_menos,proporcao_crianca_fora_escola_0_5,proporcao_escola_5_6,proporcao_crianca_fora_escola_6_14,proporcao_maternidade_10_17,maternidade_crianca_15_menos,proporcao_maternidade_fundamental_incompleto_crianca_15_menos,proporcao_analfabetismo_15_mais,proporcao_analfabetismo_18_mais,proporcao_analfabetismo_25_mais,proporcao_responsavel_fundamental_incompleto,proporcao_anos_finais_11_13,proporcao_fundamental_completo_15_17,proporcao_fundamental_completo_18_mais,proporcao_medio_completo_18_20,populacao_ocupada_trabalho,proporcao_ocupado_fundamental_18_mais,proporcao_ocupado_medio_18_mais,proporcao_ocupado_superior_18_mais,proporcao_desocupado_15_24,proporcao_desocupado_18_mais,proporcao_ocupados_informal_18_mais,proporcao_carteira_18_mais,proporcao_sem_carteira_18_mais,proporcao_setor_publico_18_mais,proporcao_empreendedor_18_mais,proporcao_empregador_18_mais,proporcao_mercado_formal_18_mais,proporcao_atividade_10_14,pea_10_mais,pea_10_14,pea_15_17,pea_18_mais,expectativa_vida,indice_gini,populacao_0_1,populacao_1_3,populacao_4,populacao_5,populacao_6,populacao_6_10,populacao_6_17,populacao_11_13,populacao_11_14,populacao_12_14,populacao_15_mais,populacao_15_17,populacao_15_24,populacao_16_18,populacao_18_mais,populacao_18_20,populacao_18_24,populacao_19_21,populacao_25_mais,populacao_65_mais
0,RS,4314902,total,1431490200130,Auxiliadora,2000,RS,4314902,total,total,total,0.133,0.002,0.244,0.151,1431490200130,Auxiliadora,0.866,0.884,0.776,0.948,0.829,0.751,muito alto,0.00,100.00,9.07,0.28,0.00,2916.92,4332.52,1.02,75.72,156.12,6.47,None,0.38,None,36.80,1.20,13.88,9.8,11.36,54.11,82.59,2.35,1.98,None,21.04,0.60,0.61,0.64,13.18,77.08,70.53,82.88,70.37,None,90.90,82.77,47.34,1.60,8.60,10.49,38.69,11.01,11.24,25.76,12.28,75.69,1.86,0,10,118,5867,78.04,0.50,66,244,74,77,68,404,1303,337,435,332,8685,464,1668,510,8221,530,1204,549,7017,1386
1,RS,4314902,total,1431490200010,Belém Velho : Hospital Parque Belém,2000,RS,4314902,total,total,total,0.354,0.340,0.397,0.326,1431490200010,Belém Velho : Hospital Parque Belém,0.668,0.820,0.513,0.707,0.514,0.513,médio,14.67,99.89,28.64,0.83,0.79,649.74,1158.41,0.91,77.36,169.07,26.20,None,1.24,None,51.07,1.96,8.76,15.1,17.54,78.76,60.46,4.36,1.37,None,40.71,4.58,4.73,5.70,21.64,76.74,45.67,51.43,22.18,None,58.42,29.99,2.13,8.99,13.83,31.78,55.00,13.81,5.26,23.21,1.81,70.72,3.98,0,7,43,931,74.22,0.48,23,98,27,34,23,143,387,106,135,101,1377,109,324,119,1268,100,215,94,1053,161
2,RS,4314902,total,1431490200251,Espírito Santo : Guaranis,2000,RS,4314902,total,total,total,0.173,0.000,0.299,0.220,1431490200251,Espírito Santo : Guaranis,0.813,0.862,0.730,0.852,0.744,0.723,muito alto,0.00,99.95,21.06,0.00,0.00,1603.68,2327.03,1.37,69.24,134.26,8.42,None,0.43,None,41.85,1.28,8.56,11.4,13.28,57.36,72.12,3.88,2.59,None,22.11,3.43,3.55,4.21,18.70,86.91,73.87,74.41,56.44,None,84.34,69.92,24.69,2.72,11.58,20.13,46.24,13.38,11.30,24.05,3.65,69.97,3.19,0,8,50,1661,76.75,0.49,37,138,40,55,37,216,576,141,187,139,2540,173,614,184,2367,198,441,198,1926,275
3,RS,4314902,total,1431490200175,Jardim Carvalho : Colina do Prado / Grécia,2000,RS,4314902,total,total,total,0.513,0.436,0.647,0.456,1431490200175,Jardim Carvalho : Colina do Prado / Grécia,0.514,0.723,0.306,0.614,0.329,0.295,muito baixo,28.99,99.78,51.27,3.08,2.26,365.67,790.48,1.81,73.51,136.31,52.57,None,1.55,None,67.80,2.83,2.46,26.1,30.37,88.77,32.20,12.17,4.74,None,72.10,9.06,9.79,11.30,56.81,48.77,22.05,32.91,14.83,None,37.68,14.15,1.32,16.73,18.94,46.25,52.02,20.51,3.39,21.42,1.05,61.19,2.95,0,13,111,1688,68.41,0.50,103,373,113,130,98,492,1073,266,349,261,2551,232,807,259,2319,245,575,230,1744,101
4,RS,4314902,total,1431490200139,Partenon : Carlos De Laet,2000,RS,4314902,total,total,total,0.391,0.407,0.403,0.365,1431490200139,Partenon : Carlos De Laet,0.687,0.828,0.540,0.727,0.536,0.541,médio,21.89,100.00,29.04,0.07,1.04,736.22,1341.33,0.76,74.12,161.11,22.22,None,0.89,None,50.97,1.91,10.84,14.4,16.75,85.61,48.86,3.52,1.53,None,53.62,4.55,4.77,5.76,30.46,81.56,47.04,53.64,39.09,None,62.58,38.27,5.24,6.58,17.97,34.13,52.70,13.85,5.39,24.42,2.75,66.42,4.22,0,6,35,946,74.66,0.48,33,92,32,41,26,129,354,83,117,88,1493,108,347,106,1385,98,239,103,1146,210
5,RS,4314902,total,1431490200143,Partenon : Vila Santa Clara,2000,RS,4314902,total,total,total,0.410,0.402,0.469,0.359,1431490200143,Partenon : Vila Santa Clara,0.627,0.777,0.479,0.662,0.447,0.495,baixo,21.16,100.00,31.87,0.25,0.00,493.05,911.31,0.80,78.96,151.79,33.90,None,1.29,None,55.47,2.57,5.54,19.6,22.80,82.58,56.48,4.19,2.77,None,50.77,4.44,4.99,6.07,40.20,76.43,42.90,44.74,22.29,None,52.10,27.05,1.17,11.42,15.44,36.04,59.29,17.24,3.83,18.12,0.71,68.03,2.39,0,3,39,503,71.59,0.43,24,60,14,26,22,103,280,68,94,65,744,83,233,75,661,77,150,76,511,59
6,RS,4314902,total,1431490200314,Campo Novo ( bairro ),2010,RS,4314902,total,total,total,0.307,0.401,0.318,0.202,1431490200314,Campo Novo ( bairro ),0.735,0.856,0.618,0.749,0.656,0.600,alto,21.89,99.80,19.12,0.00,0.22,846.68,1242.63,1.24,76.88,165.01,11.39,None,0.83,None,41.16,1.55,6.73,11.0,12.84,63.62,53.47,2.46,3.48,None,25.46,2.85,2.99,3.44,13.21,90.20,58.37,65.55,38.09,None,74.03,48.29,7.95,4.59,4.99,22.25,57.70,10.12,4.80,23.54,2.60,72.82,8.79,0,48,127,3312,76.36,0.43,76,262,68,99,90,482,1247,319,432,322,4909,333,1040,327,4576,311,707,313,3869,426
7,RS,4314902,total,1431490200065,Cristal : Resbalo,2010,RS,4314902,total,total,total,0.300,0.404,0.340,0.158,1431490200065,Cristal : Resbalo,0.724,0.825,0.638,0.721,0.642,0.636,alto,17.84,99.21,24.08,0.44,0.04,709.69,1062.87,0.64,75.65,184.28,14.49,None,0.38,None,45.53,1.77,3.27,13.4,15.68,63.62,79.48,2.00,2.18,None,32.30,5.78,6.28,7.59,13.92,89.64,55.57,64.18,29.60,None,72.33,40.59,3.88,6.57,5.06,23.41,63.80,14.29,3.44,16.54,1.30,74.22,2.13,0,3,30,464,74.50,0.39,11,46,16,16,22,98,268,73,96,72,727,74,213,79,653,64,139,58,514,33
8,RS,4314902,total,1431490200163,Jardim São Pedro,2010,RS,4314902,total,total,total,0.075,0.000,0.121,0.103,1431490200163,Jardim São Pedro,0.871,0.916,0.810,0.890,0.848,0.792,muito alto,0.00,100.00,12.35,0.00,0.00,2028.95,2480.81,0.87,67.10,161.82,3.12,None,0.00,None,37.40,1.17,15.05,7.1,8.26,53.12,79.00,1.28,0.00,None,5.96,0.86,0.90,0.98,2.07,88.63,73.59,84.79,75.45,None,91.06,82.93,40.07,0.00,4.87,10.57,51.07,12.71,7.65,23.40,4.52,75.66,2.94,0,8,43,3011,79.93,0.47,44,97,41,31,42,206,609,174,225,162,4646,178,683,187,4468,189,505,191,3963,796
9,RS,4314902,total,1431490200243,Vila Jardim : Av. Circular / Souza Lobo,2010,RS,4314902,total,total,total,0.245,0.402,0.200,0.134,1431490200243,Vila Jardim : Av. Circular / Souza Lobo,0.781,0.881,0.695,0.778,0.684,0.701,muito alto,18.75,99.92,19.27,0.21,0.00,1012.04,1363.22,0.79,70.88,208.48,6.59,None,0.27,None,42.28,1.47,11.34,9.2,10.75,49.82,96.41,1.94,0.00,None,19.38,2.16,2.24,2.47,12.45,87.32,49.69,68.35,46.98,None,77.60,57.66,13.08,1.73,4.74,22.80,58.26,12.65,2.84,23.05,2.71,73.73,1.93,0,12,114,4373,77.88,0.42,84,249,87,103,89,523,1368,359,473,352,6746,372,1284,347,6374,361,912,403,5462,937

In [40]:
%%sql
select DISTINCT id_municipio, localidade, cep,id_endereco
from `basedosdados.br_ibge_censo_2022.cadastro_enderecos`
where id_municipio='4314902' --and left(cep,5)=91740
limit 10

Running query in 'bigquery://ufrgs-ppgc-dengue'

10 rows affected.

  id_municipio     localidade       cep id_endereco
0      4314902  COSTA E SILVA  90001970   209211176
1      4314902           LAMI  90002900    74154822
2      4314902           LAMI  90002900   225667340
3      4314902         CENTRO  90010000    73336246
4      4314902         CENTRO  90010001    73336330
5      4314902         CENTRO  90010001   224499768
6      4314902         CENTRO  90010030    73319264
7      4314902         CENTRO  90010030    73335905
8      4314902         CENTRO  90010030    73349786
9      4314902         CENTRO  90010030   110614298

In [42]:
%%sql
select DISTINCT id_municipio, localidade, cep,id_endereco
from `basedosdados.br_ibge_censo_2022.cadastro_enderecos`
where id_municipio='4314902' AND cep='91740001'
limit 20

Running query in 'bigquery://ufrgs-ppgc-dengue'

20 rows affected.

   id_municipio localidade       cep id_endereco
0       4314902  CAVALHADA  91740001    74520920
1       4314902  CAVALHADA  91740001    74520984
2       4314902  CAVALHADA  91740001    74523168
3       4314902  CAVALHADA  91740001    74523337
4       4314902  CAVALHADA  91740001    74525575
5       4314902  CAVALHADA  91740001   213555681
6       4314902  CAVALHADA  91740001    74520955
7       4314902  CAVALHADA  91740001    74520975
8       4314902  CAVALHADA  91740001    74520981
9       4314902  CAVALHADA  91740001    74523228
10      4314902  CAVALHADA  91740001    74523274
11      4314902  CAVALHADA  91740001    74525566
12      4314902  CAVALHADA  91740001    74525576
13      4314902    IPANEMA  91740001   210253644
14      4314902  CAVALHADA  91740001   213555688
15      4314902  CAVALHADA  91740001   213555726
16      4314902  CAVALHADA  91740001    74520937
17      4314902  CAVALHADA  91740001    74521166
18      4314902  CAVALHADA  91740001    74523271
19      4314902  CAVALHADA  91740001    74523287

In [ ]:
%%sql
select id_municipio,udh,nome_udh
FROM `basedosdados.br_ipea_avs.municipio`
where ano=2010 and udh <>'geral' and id_municipio='4314902'

In [ ]:
%%sql
select 
    dados.sigla_uf, 
    dados.id_municipio,
    dados.localizacao
FROM `basedosdados.br_ipea_avs.municipio` AS dados
where dados.sexo='total'
    and dados.raca='total' 
    --and dados.id_municipio=4314902
limit 10

Running query in 'bigquery://ufrgs-ppgc-dengue'

RuntimeError: If using snippets, you may pass the --with argument explicitly.
For more details please refer: https://jupysql.ploomber.io/en/latest/compose.html#with-argument


Original error message from DB driver:
(google.cloud.bigquery.dbapi.exceptions.DatabaseError) 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/ufrgs-ppgc-dengue/queries?prettyPrint=false: Name raca not found inside dados at [7:15]
[SQL: select
    dados.sigla_uf,
    dados.id_municipio,
    dados.localizacao
FROM `basedosdados.br_ipea_avs.municipio` AS dados
where dados.sexo='total'
    and dados.raca='total'

limit 10]
(Background on this error at: https://sqlalche.me/e/14/4xp6)

In [ ]:
%%sql df <<
SELECT
    dados.ano as ano,
    dados.sigla_uf AS sigla_uf,
    diretorio_sigla_uf.nome AS sigla_uf_nome,
    dados.id_municipio AS id_municipio,
    diretorio_id_municipio.nome AS id_municipio_nome,
    --dados.raca_cor as raca_cor,
    --dados.sexo as sexo,
    dados.localizacao as localizacao,
    dados.udh as udh,
    dados.nome_udh as nome_udh,
    dados.ivs as ivs,
    dados.ivs_infraestrutura_urbana as ivs_infraestrutura_urbana,
    dados.ivs_capital_humano as ivs_capital_humano,
    dados.ivs_renda_trabalho as ivs_renda_trabalho,
    dados.idhm as idhm,
    dados.idhm_l as idhm_l,
    dados.idhm_e as idhm_e,
    dados.idhm_r as idhm_r,
    dados.idhm_subescolaridade as idhm_subescolaridade,
    dados.idhm_subfrequencia as idhm_subfrequencia,
    dados.prosperidade_social as prosperidade_social,
    dados.proporcao_vulnerabilidade_socioeconomica as proporcao_vulnerabilidade_socioeconomica,
    dados.propocao_energia_eletrica as propocao_energia_eletrica,
    dados.proporcao_domicilio_densidade as proporcao_domicilio_densidade,
    dados.proporcao_sem_agua_esgoto as proporcao_sem_agua_esgoto,
    dados.proporcao_sem_coleta as proporcao_sem_coleta,
    dados.renda_per_capita as renda_per_capita,
    dados.renda_media_18_mais as renda_media_18_mais,
    dados.proporcao_sem_renda_18_mais as proporcao_sem_renda_18_mais,
    dados.renda_trabalho as renda_trabalho,
    dados.renda_per_capita_vulneravel as renda_per_capita_vulneravel,
    dados.proporcao_vulneravel as proporcao_vulneravel,
    dados.populacao_vulneravel_15_24 as populacao_vulneravel_15_24,
    dados.proporcao_vulneravel_dependente_idoso as proporcao_vulneravel_dependente_idoso,
    dados.populacao_vulneravel_e_idoso as populacao_vulneravel_e_idoso,
    dados.razao_dependencia as razao_dependencia,
    dados.fecundidade_total as fecundidade_total,
    dados.taxa_envelhecimento as taxa_envelhecimento,
    dados.mortalidade_1_menos as mortalidade_1_menos,
    dados.proporcao_mortalidade_5_menos as proporcao_mortalidade_5_menos,
    dados.proporcao_crianca_fora_escola_0_5 as proporcao_crianca_fora_escola_0_5,
    dados.proporcao_escola_5_6 as proporcao_escola_5_6,
    dados.proporcao_crianca_fora_escola_6_14 as proporcao_crianca_fora_escola_6_14,
    dados.proporcao_maternidade_10_17 as proporcao_maternidade_10_17,
    dados.maternidade_crianca_15_menos as maternidade_crianca_15_menos,
    dados.proporcao_maternidade_fundamental_incompleto_crianca_15_menos as proporcao_maternidade_fundamental_incompleto_crianca_15_menos,
    dados.proporcao_analfabetismo_15_mais as proporcao_analfabetismo_15_mais,
    dados.proporcao_analfabetismo_18_mais as proporcao_analfabetismo_18_mais,
    dados.proporcao_analfabetismo_25_mais as proporcao_analfabetismo_25_mais,
    dados.proporcao_responsavel_fundamental_incompleto as proporcao_responsavel_fundamental_incompleto,
    dados.proporcao_anos_finais_11_13 as proporcao_anos_finais_11_13,
    dados.proporcao_fundamental_completo_15_17 as proporcao_fundamental_completo_15_17,
    dados.proporcao_fundamental_completo_18_mais as proporcao_fundamental_completo_18_mais,
    dados.proporcao_medio_completo_18_20 as proporcao_medio_completo_18_20,
    dados.populacao_ocupada_trabalho as populacao_ocupada_trabalho,
    dados.proporcao_ocupado_fundamental_18_mais as proporcao_ocupado_fundamental_18_mais,
    dados.proporcao_ocupado_medio_18_mais as proporcao_ocupado_medio_18_mais,
    dados.proporcao_ocupado_superior_18_mais as proporcao_ocupado_superior_18_mais,
    dados.proporcao_desocupado_15_24 as proporcao_desocupado_15_24,
    dados.proporcao_desocupado_18_mais as proporcao_desocupado_18_mais,
    dados.proporcao_ocupados_informal_18_mais as proporcao_ocupados_informal_18_mais,
    dados.proporcao_carteira_18_mais as proporcao_carteira_18_mais,
    dados.proporcao_sem_carteira_18_mais as proporcao_sem_carteira_18_mais,
    dados.proporcao_setor_publico_18_mais as proporcao_setor_publico_18_mais,
    dados.proporcao_empreendedor_18_mais as proporcao_empreendedor_18_mais,
    dados.proporcao_empregador_18_mais as proporcao_empregador_18_mais,
    dados.proporcao_mercado_formal_18_mais as proporcao_mercado_formal_18_mais,
    dados.proporcao_atividade_10_14 as proporcao_atividade_10_14,
    dados.pea_10_mais as pea_10_mais,
    dados.pea_10_14 as pea_10_14,
    dados.pea_15_17 as pea_15_17,
    dados.pea_18_mais as pea_18_mais,
    dados.expectativa_vida as expectativa_vida,
    dados.indice_gini as indice_gini,
    dados.populacao_0_1 as populacao_0_1,
    dados.populacao_1_3 as populacao_1_3,
    dados.populacao_4 as populacao_4,
    dados.populacao_5 as populacao_5,
    dados.populacao_6 as populacao_6,
    dados.populacao_6_10 as populacao_6_10,
    dados.populacao_6_17 as populacao_6_17,
    dados.populacao_11_13 as populacao_11_13,
    dados.populacao_11_14 as populacao_11_14,
    dados.populacao_12_14 as populacao_12_14,
    dados.populacao_15_mais as populacao_15_mais,
    dados.populacao_15_17 as populacao_15_17,
    dados.populacao_15_24 as populacao_15_24,
    dados.populacao_16_18 as populacao_16_18,
    dados.populacao_18_mais as populacao_18_mais,
    dados.populacao_18_20 as populacao_18_20,
    dados.populacao_18_24 as populacao_18_24,
    dados.populacao_19_21 as populacao_19_21,
    dados.populacao_25_mais as populacao_25_mais,
    dados.populacao_65_mais as populacao_65_mais
FROM `basedosdados.br_ipea_avs.municipio` AS dados
LEFT JOIN (SELECT DISTINCT sigla,nome  FROM `basedosdados.br_bd_diretorios_brasil.uf`) AS diretorio_sigla_uf
    ON dados.sigla_uf = diretorio_sigla_uf.sigla
LEFT JOIN (SELECT DISTINCT id_municipio,nome  FROM `basedosdados.br_bd_diretorios_brasil.municipio`) AS diretorio_id_municipio
    ON dados.id_municipio = diretorio_id_municipio.id_municipio
where dados.sexo='total' and dados.raca='total'

In [ ]:
save_parquet_in_chunks(df,output,50,compression='brotli')

In [ ]:
%%sql df <<
SELECT
    dados.ano as ano,
    dados.sigla_uf AS sigla_uf,
    diretorio_sigla_uf.nome AS sigla_uf_nome,
    dados.id_municipio AS id_municipio,
    diretorio_id_municipio.nome AS id_municipio_nome,
    --dados.raca_cor as raca_cor,
    --dados.sexo as sexo,
    dados.localizacao as localizacao,
    dados.udh as udh,
    dados.nome_udh as nome_udh,
    dados.ivs as ivs,